export const testPeopleData = [
  {
    id: 1,
    firstName: 'Sue',
    lastName: 'Corson',
    email: 'DWhalley@in.gov',
    phone: '(612)211-6296',
    address: {
      streetAddress: '9792 Mattis Ct',
      city: 'Waukesha',
      state: 'WI',
      zip: '22178',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 2,
    firstName: 'Harry',
    lastName: 'Wells',
    email: 'asdf@in.gov',
    phone: '(122)211-6296',
    address: {
      streetAddress: '9792 Mattock St',
      city: 'Toronto',
      state: 'EU',
      zip: '69691',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 3,
    firstName: 'Harrison',
    lastName: 'Wells',
    email: 'agseg@in.gov',
    phone: '(632)221-6296',
    address: {
      streetAddress: '2222 Hello Ct',
      city: 'Madrid',
      state: 'MI',
      zip: '11111',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 4,
    firstName: 'HR',
    lastName: 'Wells',
    email: 'czxgvzxcv@in.gov',
    phone: '(612)223-1234',
    address: {
      streetAddress: '3333 Acer St',
      city: 'NYC',
      state: 'NY',
      zip: '22222',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 5,
    firstName: 'Eobard',
    lastName: 'Thawne',
    email: 'thawne@in.gov',
    phone: '(612)233-6296',
    address: {
      streetAddress: '9792 Future St',
      city: 'Central City',
      state: 'CC',
      zip: '33333',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 6,
    firstName: 'Barry',
    lastName: 'Allen',
    email: 'allen@in.gov',
    phone: '(613)211-6296',
    address: {
      streetAddress: '9792 Heckley St',
      city: 'Central City',
      state: 'CC',
      zip: '44444',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 7,
    firstName: 'Oliver',
    lastName: 'Quinn',
    email: 'quinn@in.gov',
    phone: '(712)211-6296',
    address: {
      streetAddress: '6776 Infantino St',
      city: 'Starling City',
      state: 'SC',
      zip: '55555',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 8,
    firstName: 'Slade',
    lastName: 'Wilson',
    email: 'wilson@in.gov',
    phone: '(812)211-6296',
    address: {
      streetAddress: '9792 Aussie St',
      city: 'Sydney',
      state: 'AU',
      zip: '66666',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 9,
    firstName: 'Malcolm',
    lastName: 'Merlin',
    email: 'marlin@in.gov',
    phone: '(912)211-6296',
    address: {
      streetAddress: '9792 Dark St',
      city: 'Starling City',
      state: 'CC',
      zip: '55555',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 10,
    firstName: 'Hunter',
    lastName: 'Zolomon',
    email: 'zolomon@in.gov',
    phone: '(112)211-6296',
    address: {
      streetAddress: '9792 Zolo Ct',
      city: 'Central City',
      state: 'CC',
      zip: '11111',
    },
    description: 'et lacus magna dolor...',
  },
];
